project_id = "xrzudhylpphnzousilye"

[functions.viacep-proxy]
verify_jwt = false

[functions.printer-queue]
verify_jwt = false

[functions.sales-chat]
verify_jwt = false

[functions.whatsapp-webhook]
verify_jwt = false

[functions.whatsapp-queue]
verify_jwt = false

[functions.support-chat]
verify_jwt = false

[functions.geocode-distance]
verify_jwt = false

[functions.universal-activation-webhook]
verify_jwt = false

[functions.create-mp-payment]
verify_jwt = false

[functions.mp-webhook]
verify_jwt = false

[functions.create-mp-subscription]
verify_jwt = false

[functions.cancel-mp-subscription]
verify_jwt = false

[functions.get-subscription-details]
verify_jwt = false

[functions.get-mp-public-key]
verify_jwt = false

[functions.check-subscription-pix]
verify_jwt = false

[functions.check-pix-status]
verify_jwt = false

[functions.generate-pix-payload]
verify_jwt = false

[functions.verify-pix-payment]
verify_jwt = false

[functions.create-admin-user]
verify_jwt = false
