project_id = "xrzudhylpphnzousilye"

[functions.viacep-proxy]
verify_jwt = false

[functions.printer-queue]
verify_jwt = false

[functions.sales-chat]
verify_jwt = false

[functions.whatsapp-webhook]
verify_jwt = false

[functions.whatsapp-queue]
verify_jwt = false

[functions.support-chat]
verify_jwt = false

[functions.geocode-distance]
verify_jwt = false
